name: Config Import Missing Content
description: Automatically creates missing content entities that are dependencies in config.
package: Custom
type: module
core: 8.x
core_version_requirement: ^8 || ^9
